name: Lint

permissions: read-all

on:
  pull_request:

jobs:
  azlint:
    name: AZLint
    runs-on: ubuntu-latest
    container: matejkosiarcik/azlint:0.4.5
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0 # Full git history is needed to get a proper list of changed files

      - name: Run AZLint
        run: |
          if [ "$GITHUB_REF_NAME" = main ]; then
            azlint
          else
            azlint # --only-changed # TODO: Fix
          fi
