name: Build and Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.4

      - name: Set up QEMU ğŸ§©
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx ğŸ§©
        uses: docker/setup-buildx-action@v1.3.0

      - name: Login to DockerHub ğŸ—
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # TODO: add github container registry as another publishing target

      # - name: Build and push ğŸ”§
      #   uses: docker/build-push-action@v2.5.0
      #   with:
      #     platforms: linux/amd64
      #     push: true
      #     tags: |
      #       matejkosiarcik/azlint:dev
